
import Router from 'express';
import { createUser, loginUser, profileInfo } from './controllers/user';
import { getRandomRecipe, getRecipeByCuisine, addRecipe } from './controllers/recipes';

const router = Router.Router();
// recipe routes
// gets random "wildcard" recipe
router.get('/recipe', getRandomRecipe);
// gets recipe based on cuisine type generated by user food pref & difficulty selected
router.get('/recipe/:cuisineTag/:difficulty', getRecipeByCuisine);
// fill db
router.post('/recipe', addRecipe);

// user routes
// register new user
router.post('/register', createUser);
// login user
router.post('/login', loginUser);
// view profile info once authenticated
router.get('/profile', profileInfo);

export default router;